Repository Devamani11D/salt-app-kickstart, pull requests merged in 2024-10, with the labels that each got.

#10 added fancy pattern
  cli.js
  package-lock.json
  package.json
  templates/appheader/AppHeader.js
Labels: level-2, hacktoberfest-accepted, gssoc-ext

#18 Added Program termination on Control + C
  cli.js
  templates/login/Login.js
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest, gssoc-ext, level2

#22 Fixed : "auto-label" GitHub workflow
  .github/workflows/auto-label.yml
Labels: level3, hacktoberfest-accepted, hacktoberfest, gssoc-ext, automation
